In [121]:
#print the numbers from 1 to 100, except that if the number is divisible by 3 print "fizz", 
#if it's divisible by 5 print "buzz", and if it's divisible by 15 print "fizzbuzz".

import numpy as np
import tensorflow as tf

In [122]:
#define output as one hot encoding
def output(X):
    if X % 15 == 0:
        return np.array([0, 0, 0, 1])
    if X % 5 == 0:
        return np.array([0, 0, 1, 0])
    if X % 3 == 0:
        return np.array([0, 1, 0, 0])
    else:
        return np.array([1,0,0,0])

In [123]:
def Result(X):
    return ["No", "fizz", "buzz", "fizzbuzz"][X]

In [124]:
#binary encode the digits
def bin_encode(num, digits):
    return np.array([num >> d & 1 for d in range(digits)])

In [125]:
numDigits = 10
X = np.array([bin_encode(x, numDigits) for x in range(101, 2 ** 10)])
print X.shape

Y = np.array([output(x) for x in range(101, 2 ** 10)])
print Y.shape

(923, 10)
(923, 4)


In [126]:
hidden = 100
outputN = 4
learningRate = .05

In [127]:
#input
tf_x = tf.placeholder('float', [None, numDigits])
tf_y = tf.placeholder('float', [None, outputN])

In [128]:
#weights and biases
def weightBias(input, output):
    w = tf.Variable(tf.random_normal([input, output]))
    b = tf.Variable(tf.random_normal([output]))
    return w, b

In [129]:
#we will have 1 hidden layer
w1, b1 = weightBias(numDigits, hidden)
w2, b2 = weightBias(hidden, outputN)

In [130]:
#prediction
def model(X, w1, b1, w2, b2):
    h1 = tf.nn.relu(tf.matmul(X, w1) + b1)
    return tf.matmul(h1, w2) + b2

In [131]:
pred = model(tf_x, w1, b1, w2, b2)
cost = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(pred, tf_y))
optimizer = tf.train.GradientDescentOptimizer(learningRate).minimize(cost)
accuracy = tf.reduce_mean(tf.cast(tf.equal(tf.argmax(pred,1),tf.argmax(tf_y,1)), "float"))

In [132]:
with tf.Session() as sess:
    tf.initialize_all_variables().run()

    steps = 10000
    batch = 128
    for step in range(steps):
        p = np.random.permutation(range(len(X)))
        trX, trY = X[p], Y[p]
        
        for start in range(0, len(X), batch):
            end = start + batch
            
            sess.run(optimizer, feed_dict={tf_x : trX[start:end], tf_y: trY[start:end]})
        
        #define accuracy on training data
        
        #print step, sess.run(accuracy, feed_dict={tf_x: trX, tf_y: trY})
    
    #print final accuracy on training data
    print 'accuracy ', sess.run(accuracy, feed_dict={tf_x: X, tf_y: Y})
    predInput = np.array([bin_encode(x, numDigits) for x in range(1, 101)])
    predOutput = sess.run(pred, feed_dict={tf_x: predInput})
    
    predictO = np.argmax(predOutput, 1)
    print predictO
    

accuracy  1.0
[0 0 1 0 2 1 0 2 1 0 0 1 0 0 3 0 0 1 0 2 1 0 0 1 0 0 1 0 0 1 1 0 1 2 2 1 0
 0 1 2 0 1 0 0 3 0 0 1 0 2 1 0 1 1 2 0 1 0 0 3 0 0 1 0 2 1 0 0 1 0 0 2 0 0
 3 0 0 1 0 2 1 0 0 1 2 0 1 0 0 3 0 0 0 0 2 1 0 2 1 2]


In [133]:
for a, x in np.ndenumerate(predictO):
    print a[0]+1, Result(x)

1 No
2 No
3 fizz
4 No
5 buzz
6 fizz
7 No
8 buzz
9 fizz
10 No
11 No
12 fizz
13 No
14 No
15 fizzbuzz
16 No
17 No
18 fizz
19 No
20 buzz
21 fizz
22 No
23 No
24 fizz
25 No
26 No
27 fizz
28 No
29 No
30 fizz
31 fizz
32 No
33 fizz
34 buzz
35 buzz
36 fizz
37 No
38 No
39 fizz
40 buzz
41 No
42 fizz
43 No
44 No
45 fizzbuzz
46 No
47 No
48 fizz
49 No
50 buzz
51 fizz
52 No
53 fizz
54 fizz
55 buzz
56 No
57 fizz
58 No
59 No
60 fizzbuzz
61 No
62 No
63 fizz
64 No
65 buzz
66 fizz
67 No
68 No
69 fizz
70 No
71 No
72 buzz
73 No
74 No
75 fizzbuzz
76 No
77 No
78 fizz
79 No
80 buzz
81 fizz
82 No
83 No
84 fizz
85 buzz
86 No
87 fizz
88 No
89 No
90 fizzbuzz
91 No
92 No
93 No
94 No
95 buzz
96 fizz
97 No
98 buzz
99 fizz
100 buzz


In [134]:
print predOutput

[[  9.46161366e+00   9.92488742e-01   4.89455271e+00  -1.33804440e+00]
 [  1.18323069e+01   9.00795078e+00   5.21169138e+00   5.65806007e+00]
 [  1.05281925e+01   1.23003187e+01   2.56268048e+00   6.42840862e+00]
 [  1.33232155e+01  -2.94750881e+00   1.92928946e+00   1.05215693e+00]
 [  5.49795008e+00   2.23925138e+00   7.55400372e+00   2.35140371e+00]
 [  1.48877239e+01   1.62534657e+01   2.52598929e+00   8.98688793e+00]
 [  1.92085457e+01   8.95738506e+00   9.09469795e+00   3.36614323e+00]
 [  8.22444344e+00  -5.29129362e+00   1.14870872e+01  -5.91112804e+00]
 [  9.23134625e-01   4.86369610e+00   9.42423224e-01  -8.09382534e+00]
 [  1.67163448e+01   5.04297543e+00   1.00424852e+01   1.67954159e+00]
 [  1.79406147e+01   2.35665607e+00   1.14263189e+00   2.28512192e+00]
 [  2.06353828e-01   9.03208637e+00   5.75669718e+00  -1.38665628e+00]
 [  7.46564579e+00  -5.05208349e+00  -8.07127953e-01   7.39978015e-01]
 [  1.84843388e+01   6.88456011e+00   6.51645041e+00   9.85177422e+00]
 [  8.